# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’10.2’

target 'cocopodsDemo' do
  pod 'Alamofire', '~> 4.4'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cocopodsDemo

  target 'cocopodsDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cocopodsDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
